### ISSUE TITLE
Reverse show avatar settings to hide avatar settings

### ISSUE THREAD

**Issue by MasterOdin** [MasterOdin/salr-redux#86]
Under Thread Options, there is:

* Show User Avatar/Title
* Show User Avatar's Image

These default to true. Unlike most (all) other settings, unchecking the box turns on SALR behavior (not showing avatars) instead of enabling it turns off SALR behavior. I believe these should be reversed to be inline with how the other settings work, such that checking the box would turn on the SALR behavior. As such, I propose renaming them to:

* Hide User Avatar/Title
* Hide User Avatar's Image

with the behavior changed accordingly.

@astral-sa thoughts?

**Comment by astral-sa** [comment]
Yeah, that sounds good. Easy fix if it's just the UI getting changed and it'll be much easier for users to see what SALR is or isn't doing just by looking at which ones are checked.
